#!/bin/bash
# Bismark Device Installation script - NoxBox 
#
# author: walter.dedonato@unina.it

DEVHOST_PUB_KEY=~/.ssh/id_rsa.pub
AUTHORIZED_KEYS="../keys/authorized_keys"
KNOWN_HOSTS="../keys/known_hosts"
DEVICE_SSH_KEY="../keys/bismark"
ROOT_PASS=$(md5sum <<< bismark | cut -d" " -f1)
PASS="sleep 1; echo $ROOT_PASS;"
PARTITION="hda2"
USERNAME=root
PLATFORM=$(uname -nm | tr ' ' '_')

# Parse options
while getopts 'd:' flag; do
	case $flag in
	d)
		PARTITION=$OPTARG
	;;
	*)
		echo "Unknown option: $flag $OPTARG"
		help
	;;
	esac
done
shift $(( OPTIND - 1 ))

# Command line check
if [ ! $1 ]; then
	cat <<-end
		usage: $(basename $0) [options] <dev_id>"
	
		Options:
		       -d <partition>      set flash card partition (default: hda2)
	end
	exit
fi

if [ ${#1} -gt 15 ]; then
	echo 'ERROR: Device name longer than 15 characters!'
	exit
fi

## Installation ##

echo "Installing Bismark on NoxBox device $1..."

echo -n "Setting rc.local and mounting storage partition..."
cat >/tmp/rc.local <<-end
	$(head -13 /etc/rc.local)

	# Mount storage partition
	echo "/dev/$PARTITION /root ext2 rw,user,noatime,exec 0 0" > /etc/fstab
	mount -a
	crontab /root/conf/crontab

	exit 0
end
chmod +x /tmp/rc.local
mv /tmp/rc.local /etc
touch /tmp/void && crontab /tmp/void && rm /tmp/void
/noxbox/bin/persist_files /etc/rc.local /var/spool/cron/crontabs/root
/etc/rc.local 2>/dev/null
echo done

# Extract update package
tar -C /root -xzvf ${PLATFORM}_update.tgz

# Enter root home directory
cd /root

echo -n "Adding SSH public and host keys..."
mkdir -p .ssh 
ln -sf $AUTHORIZED_KEYS ~/.ssh/authorized_keys
ln -sf $KNOWN_HOSTS ~/.ssh/known_hosts
echo "done"

echo -n "Copying SSH key pair..."
chmod 600 ${DEVICE_SSH_KEY}
ln -sf ${DEVICE_SSH_KEY}{,.pub} ~/.ssh
echo "done"

echo -n "Setting device id and profile..."
echo $1 > ID  
echo ". ~/conf/dev.conf" > .profile
echo "done"

echo -n "Configuring cronjobs..."
crontab conf/crontab
echo "done"

echo "Setting root password:"
( 
	sleep 1; echo $ROOT_PASS
	sleep 1; echo $ROOT_PASS
) | passwd 2>/dev/null
/noxbox/bin/persist_files /etc/shadow 2>/dev/null

echo "Configuring wireless:"
WPA_PASS=$(md5sum <<< $1 | awk '{ print $1 }')
scripts/action config "WIFI_SSID=$1&WIFI_PASS=$WPA_PASS"
echo done

echo "Installation completed"

