#!/bin/bash
# Bismark Devices Installation script
#
# author: walter.dedonato@unina.it

DEVHOST_PUB_KEY=~/.ssh/id_rsa.pub
SERVER_PUB_KEY="server/keys/bismark_srv.pub"
SERVER_HOST_KEY="device/keys/known_hosts"
DEVICE_SSH_KEY="device/keys/bismark"
ROOT_PASS=$(md5sum <<< bismark | cut -d" " -f1)
PASS="sleep 1; echo $ROOT_PASS;"
VERSION=$(svn info | awk '/^Rev/{ print $2 ; exit }')

# Command line check
if [ ! $2 ]; then
	cat <<-end
		usage: $(basename $0) <address> <dev_id> [port]"
		
		Device ids:
		       LSx = Linksys WRT54GL (OpenWRT Kamikaze 8.09.1)
		       NBx = NoxBox (Debian Lenny 5.0.4)
	end
	exit
fi

# Custom port
if [ $3 ]; then
	OPT="-i ~/bismark/server/keys/bismark_srv -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p $3"
fi

# Device specific options selection
case ${2:0:2} in
LS)
	echo "Installing Bismark on Lynksys WRT54GL router ($1 $2)..."
	echo "-- if requested insert \"$ROOT_PASS\" password --"
	suffix="ls"
	crontab="/etc/crontabs/root"
	auth_keys="/etc/dropbear/authorized_keys"
;;
NB)
	echo "Installing Bismark on NoxBox router ($1 $2)..."
	echo "-- if requested insert \"n0xb0xr0x\" password --"
	suffix="nb"
	crontab="/etc/cron.d/bismark"
	auth_keys="~/.ssh/authorized_keys"
;;
*)
	echo "Model ${2:0:2} unknown"
	exit
;;
esac

# Installation
if [ $suffix == ls ] && nc -z $1 23 ; then
	echo "Setting root password and NVRAM options:"
	sleep 1
	nc -q 1 -i 3 $1 23 <<-end
		{ $PASS $PASS } | passwd
		nvram set boot_wait=on
		nvram set boot_time=10
		nvram commit && reboot
	end
	
	echo -n "Waiting for reboot"
	for ((i=0; i<10; i++)); do sleep 1; echo "."; done
	echo "done"
fi

echo -n "Adding SSH public and host keys..."
ssh $OPT root@$1 " 
	mkdir -p .ssh 
	echo \"$(cat $SERVER_PUB_KEY $DEVHOST_PUB_KEY)\" > $auth_keys
"
ssh $OPT root@$1 "echo \"$(cat $SERVER_HOST_KEY)\" > ~/.ssh/known_hosts"
echo "done"

echo "Copying SSH key pair:"
scp $OPT ${DEVICE_SSH_KEY}_$suffix{,.pub}  root@$1:~/.ssh 

echo "Copying files:"
(cd device; tar -cf - conf/* scripts/* | ssh $OPT root@$1 'tar -xvf -')

echo -n "Setting device id and software version..."
ssh $OPT root@$1 "echo $2 > ID ; echo $VERSION > VERSION"
echo "done"

if [ $suffix == ls ]; then
	echo "Installing netcat package:"
	wget -O /tmp/netcat.ipk "http://downloads.openwrt.org/kamikaze/8.09.1/brcm-2.4/packages/netcat_0.7.1-1_mipsel.ipk"
	scp $OPT /tmp/netcat.ipk root@$1:/tmp
	ssh $OPT root@$1 "opkg install /tmp/netcat.ipk ; rm /tmp/netcat.ipk"

	echo -n "Configuring cronjobs..."
	ssh $OPT root@$1 "echo \"*/1 * * * * /root/scripts/probe\" > $crontab"
	echo "done"

	echo -n "Starting crond daemon..."
	ssh $OPT root@$1 "/etc/init.d/cron enable ; pgrep crond >/dev/null || /etc/init.d/cron start"
	echo done
fi

if [ $suffix == nb ]; then
	echo -n "Configuring cronjobs..."
	ssh $OPT root@$1 "echo \"*/1 * * * * root /root/scripts/probe\" > $crontab"
	echo "done"

	echo "Setting root password:"
	ssh $OPT root@$1 "{ $PASS $PASS } | passwd"	

	echo "Persisting changes to flash memory:" 
	ssh $OPT root@$1 "/noxbox/bin/persist_changes"
fi

echo "Installation completed"

