#!/bin/sh
# Bismark ping wrapper
#
# author: walter.dedonato@unina.it

# Load configuration files
. ~/conf/dev.conf

# Help screen
[ $1 ] || { echo "usage: $(basename $0) <dst_ip>" ; exit ; }

# Options selection
opts+="-c $PING_COUNT"
opts+=" -s $PING_PSIZE"
opts+=" -W $PING_TIMEOUT"
[ ${DEVID:0:2} == LS ] || opts+=" -i $PING_INTERVAL"

# Execute ping
ping $opts $1 | awk -F"=|ms" '/ttl/{ print $4 }'
