#!/bin/sh
# Transfers files to the bismark server
#
# author: walter.dedonato@unina.it

# Load configuration file
. ~/conf/dev.conf

# Help screen
[ $1 ] || { echo "usage: $(basename $0) <file1> [...]" ; exit ; }

# Copy files using scp
for file in $*; do
	scp -i $SSH_KEY $file $USER@$SERVER:~/bismark/device/$file
done

