#!/bin/sh
# Transfers files to the bismark server
#
# author: walter.dedonato@unina.it

# Load configuration file
. ~/conf/dev.conf

# Help screen
[ $2 ] || { echo "usage: $(basename $0) <server_path> <file1> [...]" ; exit ; }

# Copy files using scp
path=$1
shift
scp -i $SSH_KEY $* $USER@$SERVER:~/$path

