#!/bin/sh
# Bismark traceroute wrapper
#
# author: walter.dedonato@unina.it

# Load configuration files
. ~/conf/dev.conf

# Help screen
[ $1 ] || { echo "usage: $(basename $0) <dst_ip>" ; exit ; }

case $DEVID in
NB*) traceroute -n -T -q1 $1 | awk '! /trace/{ print "<hop id="$1" ip="$2" rtt="$3" />" }' ;;
LS*) traceroute -n -q1 $1 | awk '! /trace/{ print "<hop id="$1" ip="$2" rtt="$3" />" }' ;;
esac
