#!/bin/bash
# Bismark traceroute wrapper
#
# author: walter.dedonato@unina.it

# Load configuration files
. ~/conf/dev.conf

# Help screen
[ $1 ] || { echo "usage: $(basename $0) <dst_ip>" ; exit 1 ; }

# AWK filters
filter_std='! /trace/{ print "<hop id="$1" ip="$2" rtt="$3" />" }'
filter_tcp='{ rtt=$3 } ; /\[.*\]/{ rtt=$4 } ; { print "<hop id="$1" ip="$2" rtt="rtt" />" }'

# Select traceroute type
case $TR_TYPE in
UDP)  
	cmd="traceroute"
	opts="-n -q1"
	filter=$filter_std
;;
TCP)
	if which tcptraceroute > /dev/null; then
		cmd="tcptraceroute"
		opts="-n -q1"
		filter=$filter_tcp
	else
		cmd="traceroute"
		opts="-n -q1 -T"
		filter=$filter_std
	fi
	[ $(id -u) -eq 0 ] || cmd="sudo $cmd"
;;
ICMP)
	cmd="traceroute"
	opts="-n -q1 -I"
	filter=$filter_std
	[ $(id -u) -eq 0 ] || cmd="sudo $cmd"
;;
esac

# Run traceroute
$cmd $opts $1 | awk "$filter"

