#!/bin/sh
# Bismark traceroute wrapper
#
# author: walter.dedonato@unina.it

# Load configuration files
. ~/conf/dev.conf
[ -e ~/local.conf ] && . ~/local.conf

# Help screen
[ $1 ] || { echo "usage: $(basename $0) <dst_ip>" ; exit ; }

case $DEVID in
NB*|WS*)
    case $TRACEROUTE_TYPE in
    UDP)  opt="-p 53" ;;
    TCP)  opt="-T" ;;
    ICMP) opt="-I" ;;
    esac
    traceroute -n $opt -q1 $1 | awk '! /trace/{ print "<hop id="$1" ip="$2" rtt="$3" />" }' 
;;
LS*) tcptraceroute -n -q1 $1 | awk '{ rtt=$3 } ; /\[.*\]/{ rtt=$4 } ; { print "<hop id="$1" ip="$2" rtt="rtt" />" }' ;;
esac
