#!/bin/bash
# Bismark wget wrapper
#
# author: walter.dedonato@unina.it

# Load configuration files
. ~/conf/dev.conf

# Help screen
[ $2 ] || { echo "usage: $(basename $0) <url> <up|dw>" ; exit ; }



case $2 in
up) echo ok ;;
dw) wget -O /dev/null "$1" --progress=bar:force 2>&1 | awk 'BEGIN{RS=" "} /[0-9]+K\/s/{print int($1)}' ;;
esac
