#!/bin/bash
# Cache persistently measurements results
#
# author: walter.dedonato@unina.it

# Load configuration file
. ~/conf/dev.conf
. ~/scripts/functions

cd /tmp/measure
rename_dump
tar --remove-files -czvf ~/cache/${DEVICE_ID}_$(date +%s).tgz *.*
