#!/bin/bash
# Ausiliary functions library
#
# author: walter.dedonato@unina.it

# Modifies configuration files option
# $1 = configuration file
# $2 = option
# $3 = value
mod_conf ()
{
	if [ $3 ]; then
		# Modify value
		sed -i -e "/^$2=/ s/=.*/=$3/" $1
	else
		# Remove option
		sed -i -e "/^$2=/ d" $1
	fi
}

# Log output destination
# $1 = action
output ()
{
        if [ $REMOTE ]; then
                ( echo "$DEVICE_ID log $1 $(date +%s)" ; cat ) | nc -u $NC_OPTS $SERVER $PROBE_PORT
        else
                cat
        fi
}

# Rename dump files
rename_dump ()
{
	# Rename features dump files
	( cd /tmp/measure/
	  for file in $(find -name "*.dump"); do
		mv $file ${DEVICE_ID}_${file:2}
	  done
	)
}

# Get public IP
get_ip ()
{
	if [ -e /tmp/ip ] && [ $(grep -c '^[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*$' /tmp/ip) -ge 1 ]; then
		src=$(cat /tmp/ip)
	else
		src=$(ifconfig $WAN_IF | awk '/inet:/{ print substr($2,6) }')
	fi
}
