#!/bin/bash
# Ausiliary functions library
#
# author: walter.dedonato@unina.it

# Modifies configuration files option
# $1 = configuration file
# $2 = option
# $3 = value
mod_conf ()
{
ed $1 <<-end
	/^$2=/
	.s/=.*/=$3/
	w
	q
end
}

# Log output destination
# $1 = action
output ()
{
        if [ $REMOTE ]; then
                ( echo "$DEVICE_ID log $1 $(date +%s)" ; cat ) | nc -u $NC_OPTS $SERVER $PROBE_PORT
        else
                cat
        fi
}
