#!/bin/sh
# Send UDP probes to Bismark server and
# acts depending on the answer
#
# Currently implements:
# - Bismark server heartbeat
# - on-demand SSH tunnel
# - software update
# - information query
#
# author: walter.dedonato@unina.it

# Load configuration file
. ~/conf/dev.conf

# Probe message generator
msg () {
	echo "$DEVID ping"
	sleep 3
	return 0
}

# OS depending options
if [ -e /etc/openwrt_version ]; then
	NC_OPTS="-nuc"
else
	NC_OPTS="-q1 -nu"
fi

# Send probe and store reply
msg | nc $NC_OPTS $SERVER $PROBE_PORT > /tmp/reply

# Parse reply
read cmd value < /tmp/reply
case $cmd in 
fwd)
	# on-demand SSH tunnel
	ssh -N -i $SSH_KEY -R $value:127.0.0.1:22 $USER@$SERVER &
;;
pong)
	# Server heartbeat
	date +%s > /tmp/server_last
;;
update)
	# Software update
	echo "$(date) - Updating $value" > /tmp/update.log
	case $value in
	all)
		ssh -i $SSH_KEY $USER@$SERVER 'cd bismark/device; tar -cf - conf/* scripts/*' | tar -xvf - >> /tmp/update.log
		ssh -i $SSH_KEY $USER@$SERVER 'svn info bismark | awk "/^Rev/{ print \$2 ; exit }"' > ~/VERSION
	;;
	*)
		ssh -i $SSH_KEY $USER@$SERVER 'cd bismark/device; tar -cf - '$value | tar -xvf - >> /tmp/update.log
	;;
	esac
	echo "$(date) - Update completed" >> /tmp/update.log
	cat /tmp/update.log | nc $NC_OPTS $SERVER $((PROBE_PORT+1))
;;
info)
	# Info reply
	sleep 1
	nc $NC_OPTS $SERVER $((PROBE_PORT+1)) <<-end
		Version: $(cat ~/VERSION)
	end
;;
esac
