#!/bin/sh
# Starts a recovery shell if unable to probe the server 
# open a tunnel for 15 minutes each 30 minutes 
#
# author: walter.dedonato@unina.it

# Load configuration file
. ~/conf/dev.conf

[ -e /tmp/server_last ] || echo `date +%s` > /tmp/server_last

# Work only if last timestamp is more than 15 minutes old
if [ $((`date +%s` - `cat /tmp/server_last`)) -gt 900 ]; then
    if [ -e /tmp/tunnel ]; then
        port=$(cat /tmp/tunnel)
        pid=$(ps ax | awk "/ssh.*-R $port:127/{print \$1}" | head -1)
        kill -9 $pid
        ps $pid >/dev/null && rm /tmp/tunnel
    else
        RANDOM=$(( `date +%s` % 32767 ))
        port=$(( RANDOM % 5000 + 5000 ))
        ssh -i $SSH_KEY $USER@$SERVER '. etc/bdm.conf ; bin/sqlite3 -list $BDM_DB "INSERT INTO tunnels VALUES(\"'$DEVID'\",'$port','$(date +%s)');"'
        echo $port > /tmp/tunnel
        ssh -N -i $SSH_KEY -R $port:127.0.0.1:22 $USER@$SERVER 
    fi
fi

