#!/bin/bash
# Starts a recovery shell if unable to probe the server 
# open a tunnel for 15 minutes each 30 minutes 
#
# author: walter.dedonato@unina.it

# Load configuration file
. ~/conf/dev.conf

[ -e /tmp/server_last ] || echo `date +%s` > /tmp/server_last

# Close pre-existing recovery tunnel
if [ -e /tmp/tunnel ]; then
	pid=$(cat /tmp/tunnel)
	kill -9 $pid
	ps $pid >/dev/null && rm /tmp/tunnel
	echo `date +%s` > /tmp/server_last
fi 

# Start new tunnel only if last timestamp is more than 15 minutes old
if [ $((`date +%s` - `cat /tmp/server_last`)) -gt 900 ]; then
	RANDOM=$(( `date +%s` % 32767 ))
	port=$(( RANDOM % 5000 + 5000 ))
	ssh -i $SSH_KEY $USER@$SERVER '. etc/bdm.conf ; bdm settunnel $DEVICE_ID $port'
	ssh $KEEP_ALIVE -N -i $SSH_KEY -R $port:127.0.0.1:22 $USER@$SERVER &
	echo $! > /tmp/tunnel
fi

