#!/bin/bash
# Device startup script
#
# author walter.dedonato@unina.it

# Load configuration
. ~/conf/dev.conf

case $DEVICE_ID in
NB*)
	# Configure wireless interface channel
	grep -q ^channel= /etc/hostapd/hostapd.conf || echo channel=1 >> /etc/hostapd/hostapd.conf
	iwconfig ath0 channel $(awk -F= '/^channel/{ print $2 }' /etc/hostapd/hostapd.conf)

	# Setup dhcp log script
	echo "dhcp-script=/root/scripts/bdhcp" >> /etc/dnsmasq.conf
	/etc/init.d/dnsmasq restart
;;
LS*)
	# Create bin and lib directories on ramdisk
	mkdir /tmp/bin /tmp/lib
	ln -s /tmp/bin bin
	ln -s /tmp/lib lib
	sleep 10
	action update
;;
esac
