#!/bin/sh
# Upload measurements to the bismark server
#
# author: walter.dedonato@unina.it

# Load configuration file
. ~/conf/dev.conf

# Copy files using scp
scp -i $SSH_KEY /tmp/measure/*.xml $USER@$SERVER:~/var/data
rm /tmp/*.xml

