#!/bin/bash
# Upload measurements to the bismark server
#
# author: walter.dedonato@unina.it

# Load configuration file
. ~/conf/dev.conf

# Copy files using scp
scp -i $SSH_KEY /tmp/measure/*.xml $USER@$SERVER:~/var/data && rm /tmp/measure/*.xml

# Syncronize clock
if [ ${DEVID:0:2} == WS ]; then
	if [ $(id -u) -eq 0 ]; then
		ntpdate pool.ntp.org
	else
		sudo ntpdate pool.ntp.org
	fi
fi
