#!/bin/bash
# Upload measurements to the bismark server
#
# author: walter.dedonato@unina.it

# Load configuration file
. ~/conf/dev.conf

# Copy active measurements files
scp -i $SSH_KEY /tmp/measure/*.xml $USER@$SERVER:~/var/data && rm /tmp/measure/*.xml

# Copy passive measurements files
scp -i $SSH_KEY /tmp/measure/*.t2 $USER@$SERVER:~/var/data && rm /tmp/measure/*.t2
scp -i $SSH_KEY /tmp/measure/*.dhcp $USER@$SERVER:~/var/data && rm /tmp/measure/*.dhcp


