#!/bin/bash

# Load configuration
. ~/etc/mserver.conf

# If launched without options starts the socat listener
if [ ! $1 ]; then
	if [ $ITG_DW_PORT -le 1024 ]; then
		sudo socat TCP-LISTEN:$ITG_DW_PORT,fork,reuseaddr EXEC:"$0 run",su-d=$LOGNAME,pipes &
	else
		socat TCP-LISTEN:$ITG_DW_PORT,fork,reuseaddr EXEC:"$0 run",pipes &
	fi
	exit
fi

# Parse input
read cmd opt

case $cmd in
send)
	if [ ${opt:0:2} == "-H" ]; then
		id=$(echo $opt | md5sum | cut -c 1-10)
		echo "$id start $(date +%s) ($opt)" >> /tmp/itg_dw.log
		~/bin/ITGSend $opt 2>&1 | awk '{ "date +%s" | getline date ; print "'$id' " date " " $0 ; fflush() }' >> /tmp/itg_dw.log &
		pid=$(( $! - 1 ))
		echo "$id pid $pid" >> /tmp/itg_dw.log
	fi
;;
log)
	echo $cmd - $opt >> /tmp/itg.log
	~/bin/ITGDec $opt -j 1000 $opt.jitter -p 1000 $opt.pktloss -b 1000 $opt.bitrate 2> /dev/null
	echo bitrate
	awk '(NR > 1){ print $3 }' $opt.bitrate
	echo jitter
	awk '(NR > 1){ print $3 }' $opt.jitter
	echo pktloss
	awk '(NR > 1){ print $3 }' $opt.pktloss
	rm $opt $opt.*
;;
esac
