#!/bin/bash

# Load configuration
. ~/etc/mserver.conf

if [ ! $1 ]; then
        if [ $UPRATE_PORT -le 1024 ]; then
		( sudo socat TCP-LISTEN:$UPRATE_PORT,fork,reuseaddr EXEC:"$0 run",su-d=$LOGNAME,pipes ) &
        else
		( socat TCP-LISTEN:$UPRATE_PORT,fork,reuseaddr EXEC:"$0 run",pipes ) &
        fi
        exit
fi

ip=$SOCAT_PEERADDR

# Parse input
read cmd opt

case $cmd in
start)
	( sudo /usr/sbin/tcpdump -tt -n -i $IFNAME tcp and ip src $ip and dst port $HTTP_PORT >/tmp/$ip.rate 2>/dev/null ) &
	echo $!
;;
stop)
	sudo kill $opt

	awk '
	BEGIN{ 
		stime=0
		bytes=0  
	} 
	{ 
		if ($1 > 0) 
			ltime=$1
		if (stime == 0) 
			stime=ltime
		if (ltime - stime > 1) { 
			print bytes/125
			bytes=0
			stime=ltime
		}
		bytes += $21
	}
	END{
		if (ltime - stime > 0)
			print ((bytes/125) / (ltime - stime))
	}' /tmp/$ip.rate
	rm /tmp/$ip.rate
;;
esac


