#!/bin/bash
# Bismark ping wrapper
#
# author: walter.dedonato@unina.it

# Load configuration files
. ~/conf/dev.conf

# Help screen
[ $1 ] || { echo "usage: $(basename $0) <dst_ip>" ; exit ; }

# Options selection
opts="$opts -c $PING_COUNT"
opts="$opts -s $PING_PSIZE"
opts="$opts -W $PING_TIMEOUT"
[ ${DEVICE_ID:0:2} == LS ] || opts="$opts -i $PING_INTERVAL"

# Execute ping
ping $opts $1 | awk -F"=|ms" '/ttl/{ print $4 }'
