#!/bin/bash
# Send UDP probes to Bismark server and
# call action script depending on the answer
# Provides:
# - device heartbeat
# - UDP proxy fallback
# - startup script during boot
#
# author: walter.dedonato@unina.it

# Load configuration file
. ~/conf/dev.conf

# Probe message generator
msg () {
	echo "$DEVICE_ID ping $VERSION"
	sleep 1
	return 0
}

# Launch startup script during boot
[ -e /tmp/faults ] || startup

# Create status files
[ -e /tmp/faults ] || echo 0 > /tmp/faults
[ -e /tmp/proxy ] || echo 0 > /tmp/proxy

# Check faults count
faults=$(cat /tmp/faults)
if [ $faults -ge 20 ]; then
	proxy=$(cat /tmp/proxy)
	echo $(( (proxy + 1) % 2 )) > /tmp/proxy
	echo 0 > /tmp/faults
	faults=0
fi

# Random wait
sleep $((RANDOM % 30))

# Send probe and store reply
if [ $(cat /tmp/proxy) -eq 1 ]; then
	msg | nc -u $NC_OPTS $PROXY $PROXY_PORT > /tmp/reply
else
	msg | nc -u $NC_OPTS $SERVER $PROBE_PORT > /tmp/reply
fi

# Refresh faults count
if [ "`cat /tmp/reply`" ]; then
	echo 0 > /tmp/faults
	event uplink up
else
	echo $((++faults)) > /tmp/faults
	event uplink down
fi

# Parse reply
read cmd value < /tmp/reply
[ $cmd ] && REMOTE=on action $cmd $value

