#!/bin/sh
# Send UDP probes to Bismark server and
# acts depending on the answer
#
# Currently implements:
# - Bismark server heartbeat
# - on-demand SSH tunnel
# - light SSH tunnel shutdown
#
# author: walter.dedonato@unina.it

# Load configuration file
. ~/box.conf

# Probe message generator
msg () {
	echo "$BOXID ping"
	sleep 3
	return 0
}

# OS depending options
if [ -e /etc/openwrt_version ]; then
	NC_OPTS="-nuc"
	SSH_OPTS="-yN"
else
	NC_OPTS="-q1 -nu"
	SSH_OPTS="-N"
fi

# Send probe and store reply
msg | nc $NC_OPTS $SERVER $PROBE_PORT > /tmp/reply

# Parse reply
read cmd value < /tmp/reply
case $cmd in 
fwd)
	# on-demand SSH tunnel
	ssh $SSH_OPTS -i $SSH_KEY -R $value:127.0.0.1:22 $USER@$SERVER &
;;
pong)
	# Server heartbeat
	date +%s > /tmp/server_last
;;
stop)
	# Stop tunnel
	kill $(ps a | awk "/ssh.*-R $value:127/{print \$1}" | head -1)
;;
esac

