#!/bin/sh
# Send UDP probes to bismark server and
# open SSH tunnel if requested
#
# author walter.dedonato@gatech.edu

SERVER="143.215.131.215"
USER="bismark"
PORT="5353"
BOXID="1"

if [ $1 ]; then
	echo "ping $BOXID"
	sleep 2
	exit
fi 

$0 ping | nc -nuc $SERVER $PORT > /tmp/port

p=$(cat /tmp/port)
[ $((p)) -gt 1024 ] && ssh -y -i ~/.ssh/bismark_box -N -R $p:127.0.0.1:22 $USER@$SERVER
