#!/bin/sh
# Send UDP probes to Bismark server and
# acts depending on the answer
#
# Currently implements:
# - Bismark server heartbeat
# - on-demand SSH tunnel
#
# author walter.dedonato@gatech.edu

SERVER="143.215.131.215"
USER="bismark"
SSH_KEY=/root/.ssh/bismark_box
PORT="5353"
BOXID="1"

# Probe message generator
msg () {
	echo "$BOXID ping"
	sleep 3
	return 0
}

# Send probe and store reply
msg | nc -nuc $SERVER $PORT > /tmp/reply

# Parse reply
read cmd value < /tmp/reply
case $cmd in 
fwd)
	# on-demand SSH tunnel
	ssh -y -i $SSH_KEY -N -R $value:127.0.0.1:22 $USER@$SERVER &
;;
pong)
	# Server heartbeat
	date +%s > /tmp/server_last
;;
esac

