#!/bin/bash
# Bismark Devices Management Daemon wrapper
#
# author: walter.dedonato@unina.it

# Load configuration file
. ~/etc/bdm.conf

export VAR_DIR

# Aliases

# Help screen
# $1 = command
function help() 
{
	cat <<-end
	Syntax:

	    $(basename $0) [options] <start|stop|restart|info>
	
	Options:
	
	    -h               Print help screen
	end
	exit
}

## Main ##

# Check directories
mkdir -p $VAR_DIR/log/devices/

# Make DB
cd $DB_SRC
make create DB=$PSQL_DB
cd -

# Parse command-line
while getopts 'h' flag; do
	case $flag in
	h)
		help
	;;
	*)
		echo "Unknown option: $flag $OPTARG"
		help
	;;
	esac
done
shift $(( OPTIND - 1 ))

pid=$(pgrep bdmd.real)
ports=$(sudo netstat -lnup | awk -F"[\t: ]*" '/bdmd.real/{ print $5 }')
case $1 in
start)
	if [ "$ports" ]; then
		echo "bdmd already running on ports" $ports
	else
		echo -n "Starting bdmd..."
		bdmd.real $PROBE_PORTS >> $BDMD_LOG_FILE 2> /tmp/bdmd.debug &
		sleep 1
		[ "$(pgrep bdmd.real)" ] && echo "done" || echo "error"
	fi
;;
stop)
	if [ "$pid" ]; then 
		echo -n "Stopping bdmd..."
		kill $pid
		sleep 1
		[ "$(pgrep bdmd.real)" ] && echo "error" || echo "done" 	
	else
		echo "bdmd not running"
	fi
;;
restart)
	$0 stop
	$0 start 
;;
info)
	if [ "$pid" ]; then
		echo "bdmd listening on "$ports" (pid "$pid")"
	else
		echo "bdmd not running"
	fi
;;
*)
	help
;;
esac

