#!/bin/bash
# Bismark Restricted Shell
# 
# Only allows to execute: 
# - scp    : to upload measure results
# - rshell : add recovery tunnel to list
#
# author: walter.dedonato@unina.it

# Include configuration
. ~/etc/bdm.conf

cmd=$(echo "$SSH_ORIGINAL_COMMAND" | gawk '
	($1 == "scp") && ($(NF-1) ~ "-t") && ($NF ~ "var/data/") && ! ($NF ~ "\\.\\.") && ! /[;$`]/ { print }
	($1 == "rshell") && ! /[;$`]/ { print "bdm settunnel " $2 " " $3 }
')

$cmd

if [ "${cmd:0:3}" == "bdm" ]; then
	while [ true ]; do
		read 
	done
fi
