#!/bin/bash
# Parser for TIE netflow data
#
# author: walter.dedonato@unina.it

PATH=/home/bismark/bin:/sbin:/usr/sbin:/home/bismark/bin:/home/bismark/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/bin:/bin

# Avoid multiple instances
[ -e /tmp/t2_parser/lock ] && exit

# Parse options
while getopts 'r' flag; do
	case $flag in
	r) REMOVE="true" ;;
	*)
		echo "Unknown option: $flag $OPTARG"
		exit
	;;
	esac
done
shift $(( OPTIND - 1 ))

# Set lock file
mkdir -p /tmp/t2_parser
touch /tmp/t2_parser/lock

# Settings
[ $1 ] && DATA_DIR=$1 || DATA_DIR=~/var/data
BACKUP_DIR="$DATA_DIR/../processed/t2"
BACKUP_FILE="t2_$(date +%s).tar"
LOG_FILE="/tmp/t2_parser/$BACKUP_FILE.log"
AGGR_TABLE="FLOWS_newformat"
SMPL_TABLE="FLOWS_SAMPLES_newformat"
SQL_FILE="/tmp/t2_parser/flows.sql"

# Create backup dir
[ $REMOVE ] || mkdir -p $BACKUP_DIR 

# Process any .t2 file from DATA dir
cd $DATA_DIR
for file in $(find . -name '*.t2') ; do
	device="$(basename $file)"
	device="${device%%_*}"

	# Skip the file if it has already been parsed
	read fid tst tend <<< $(gawk '/^[0-9]/{ print $1 " " $11 " " $12; exit }' "$file")
	uid=$(mysql -NB -u root -e "SELECT a.uid FROM $AGGR_TABLE as a JOIN $SMPL_TABLE as s ON a.uid = s.uid
					WHERE a.flowid='$fid' AND a.deviceid='$device' AND s.tsstart='$tst' AND s.tsend='$tend';" bismark_live_v1)
	[ $uid ] && { 
		echo "=== $(date) - $file - SKIPPED" | tee -a $LOG_FILE 
		rm "$file"
		continue
	}

	# Parse file
	echo "=== $(date) - $file" | tee -a $LOG_FILE
	echo "START TRANSACTION;" > $SQL_FILE
	gawk -f /dev/stdin "$file" >> $SQL_FILE <<-end
		BEGIN { 
			while ((getline line < (ENVIRON["HOME"] "/etc/tie_apps.txt")) > 0) {
				split(line, app, /(\",\t+\"|,\t+\"|,\t+)/) ;
				if (app[1] ~ /^[0-9]/ ) {
					id[app[5]] = app[1] ;
					sid[app[5]] = app[2] ;
				}
			}
		}
		/^[0-9]/ && (NF == 15){
			ts = \$11;
			te = \$12;

			if (\$13 ~ /^[0-9]/) {
				appid = \$13 ;
				subid = \$14 ;
			} else {
				appid = id[\$14] ;
				subid = sid[\$14] ;
			}

			print	"INSERT INTO $AGGR_TABLE VALUES (NULL,"\$1",\"$device\", \
					INET_ATON(\""\$2"\"), \
					INET_ATON(\""\$3"\"), \
					"\$4","\$5","\$6","\$8","\$7","\$10","\$9","ts","te","appid","subid") \
				ON DUPLICATE KEY UPDATE uid=LAST_INSERT_ID(uid), \
					tsend=GREATEST("te",tsend), uppkts=uppkts+"\$8", dwpkts=dwpkts+"\$7", upbytes=upbytes+"\$10", dwbytes=dwbytes+"\$9"; \
				INSERT INTO $SMPL_TABLE \
					VALUES (LAST_INSERT_ID(), "\$8","\$7","\$10","\$9","ts","te");"
		}
	end
	echo "COMMIT;" >> $SQL_FILE

	mysql -NB -u root bismark_live_v1 < $SQL_FILE 2>> $LOG_FILE 
	if [ $REMOVE ]; then
		rm "$file"
	else
		tar -rf $BACKUP_DIR/$BACKUP_FILE --remove-files "$file"
	fi
done

[ $REMOVE ] || gzip $BACKUP_DIR/$BACKUP_FILE

# Unset lock file
rm /tmp/t2_parser/lock

