#!/bin/bash
# Parser for TIE netflow data
#
# author: walter.dedonato@unina.it

# Avoid multiple instances
[ $(pgrep -f t2_parse) ] && exit

# Settings
[ $1 ] && DATA_DIR=$1 || DATA_DIR=~/var/data
BACKUP_DIR=$DATA_DIR/old
BACKUP_FILE=t2_$(date +%s).tar
AGGR_TABLE="FLOWS"
SMPL_TABLE="FLOWS_SAMPLES"

# Create backup dir
mkdir -p $BACKUP_DIR 

# Process any .t2 file from DATA dir
cd $DATA_DIR
for file in $(find . -name '*.t2') ; do
	device=$(basename $file)
	device=${device%%_*}

	# Parse file
	echo $file
	gawk -f /dev/stdin $file > /tmp/flows.sql <<-end
		/^[0-9]/{
			ts = \$11 * 1000000
			te = \$12 * 1000000
			print	"INSERT INTO $AGGR_TABLE VALUES (NULL,"\$1",\"$device\", \
					INET_ATON(\""\$2"\"), \
					INET_ATON(\""\$3"\"), \
					"\$4","\$5","\$6","\$8","\$7","\$10","\$9","ts","te",\""\$14"\") \
				ON DUPLICATE KEY UPDATE uid=LAST_INSERT_ID(uid), \
					tsend="te", uppkts=uppkts+"\$8", dwpkts=dwpkts+"\$7", upbytes=upbytes+"\$10", dwbytes=dwbytes+"\$9"; \
				INSERT INTO $SMPL_TABLE \
					VALUES (LAST_INSERT_ID(), "\$8","\$7","\$10","\$9","ts","te");"
		}
	end
	mysql -NB -u root bismark_live_v1 < /tmp/flows.sql 2>> /tmp/t2_parse.log 
	tar -rf $BACKUP_DIR/$BACKUP_FILE --remove-files $file
done

gzip $BACKUP_DIR/$BACKUP_FILE

