#!/bin/bash
# Device actions script
# Provides:
# - on-demand SSH tunnel
# - server heartbeat
# - software update
# - configuration query/push
#
# author: walter.dedonato@unina.it

# Import configuration and functions
. $BISMARK_DIR/etc/bismark.conf
. $BISMARK_DIR/scripts/functions

# Help screen
[ $1 ] || { echo "$(basename $0) <command> [options]" ; exit ; }

# Perform action
case $1 in
fwd)	# on-demand SSH tunnel
	if [ $2 == ${2#*:} ]; then
		( ssh $KEEP_ALIVE -N -i $SSH_KEY -R $2:127.0.0.1:22 $USER@$SERVER >/dev/null 2>&1 & )
	else
		( ssh $KEEP_ALIVE -N -i $SSH_KEY -R $2 $USER@$SERVER >/dev/null 2>&1 & )
	fi
;;
pong)	# Server heartbeat
	ltime=$(date +%s)
	stime=$(( $3 + 2 ))

	# Check clock synch
	[ $stime -gt $((ltime + 1)) ] && resync=true
	[ $stime -lt $((ltime - 1)) ] && resync=true
	if [ $resync ]; then
		ltime=$stime
		date -s @$ltime
		hwclock -w
	fi
	echo $ltime > $BISMARK_DIR/var/server_last

	# Store public IP 
	echo $2 > $BISMARK_DIR/var/ip
;;
update)	# Software update

	# Skip if same version
	[ $2 ] && [ $VERSION -eq $2 ] && { echo "Device up to date" | output $1 ; exit ; }

	# Start svn update
	svn update $BISMARK_DIR | output $1

	# Apply changes
	crontab $BISMARK_DIR/etc/crontab

	# Set restart flag
	touch $BISMARK_DIR/var/restart
;;
config)
	# Modify parameters	
	if [ "$2" ]; then 
		# Parse new configuration
		IFS=$'&'
		for param in $2; do
			name=${param%=*}
			value="${param#*=}"

			# Check generic parameter validity
			grep -q "^$name=" $BISMARK_DIR/etc/{bismark,local}.conf || { echo -e "Invalid option $name\n" >&2; continue ; }

			# Assign new value to parameter
			eval "$name=\"$value\""

			if [ "$value" ]; then
				# Store parameter 
				if grep -q "^$name=" /tmp/local.conf; then
					# Substitute
					mod_conf /tmp/local.conf $name "$value"
				else
					# Append
					echo $name="$value" >> /tmp/local.conf
				fi
			elif grep -q "^$name=" /tmp/local.conf; then
				# Remove parameter from local.conf
				mod_conf /tmp/local.conf $name
			fi
		done
	fi

	# Configuration output
	set | awk -F'=' '(FNR==1){ f+=1 } /=/{ if (f == 1){a[$1]=1} else { if (a[$1] == 1) print $1 "=" $2} }' $BISMARK_DIR/etc/bismark.conf - | output $1
;;
esac

