#!/bin/bash
# Bismark arp wrapper
#
# author: walter.dedonato@unina.it

# Load configuration files
. ~/conf/dev.conf

# Dump arp table 
arp -n | awk '(NR > 1 && /ether/){ print '$(date +%s)' "\t" $1 "\t" $3}' >> /tmp/measure/${DEVICE_ID}.arp
