#!/bin/ash
# Bismark ping wrapper
#
# author: walter.dedonato@unina.it

# Load configuration files
. /etc/bismark/bismark.conf
. "$BROOT"/etc/bismark/bismark-active.conf

# Help screen
[ $1 ] || { echo "usage: $(basename $0) <dst_ip>" ; exit ; }

# Options selection
opts="$opts -c $PING_COUNT"
opts="$opts -s $PING_PSIZE"
opts="$opts -W $PING_TIMEOUT"

# Execute ping
ping $opts $1 | awk -F"=|ms" '/ttl/{ print $4 }'
