#!/bin/ash
# Starts a recovery shell if unable to probe the server 
#
# author: walter.dedonato@unina.it

# Load configuration file
. /etc/bismark/bismark.conf
. /usr/lib/bismark/functions.inc.sh

# Local config
BASE_PORT=5000
MAX_PORT=50000

[ -e /tmp/bismark/var/server_last ] || echo `date +%s` > /tmp/bismark/var/server_last

# Start new tunnel if last timestamp is more than 5 minutes old
if [ $((`date +%s` - `cat /tmp/bismark/var/server_last`)) -gt 300 ]; then
	if [ -e /tmp/bismark/var/tunnel ]; then
		# Check pre-existing recovery tunnel
		read pid < /tmp/bismark/var/tunnel
		ps $pid >/dev/null || rm /tmp/bismark/var/tunnel
	else
		# Create new recovery tunnel
		port=$(random $BASE_PORT $MAX_PORT)
		( ssh $KEEP_ALIVE -i $SSH_KEY -R $port:127.0.0.1:22 $USER@$SERVER "rshell $DEVICE_ID $port" >/dev/null 2>&1 & )
		echo $! > /tmp/bismark/var/tunnel
	fi
fi

