#!/bin/ash
# Bismark fping wrapper
#
# author: srikanth@gatech.edu

# Load configuration files
. /etc/bismark/bismark.conf
. "$BROOT"/etc/bismark/bismark-active.conf

# Help screen
[ $2 ] || { echo "usage: $(basename $0) <target_file_name> <src_ip> [mstats_param]" ; exit ; }

if [ $3 ]; then
    mstats_param="$3"
else
    mstats_param="RTT"
fi

# Options selection
opts="$opts -c $FPING_COUNT"
opts="$opts -b $FPING_PSIZE"
opts="$opts -t $FPING_TIMEOUT"
opts="$opts -p $FPING_INTERVAL"
fping_out=/tmp/bismark/active/fping-out
# Execute ping
fping $opts -f $1 2>/dev/null | awk '/ms/{print $1, $6}' > $fping_out
for i in `awk '{print $1}' $fping_out | sort -u`; do
	awk '/'$i'/{print $2}' $fping_out | "$BROOT"/usr/bin/bismark-mstats $mstats_param FPING $2 $i
done
rm $fping_out
