#!/bin/ash
# Device startup script
#
# author walter.dedonato@unina.it

# Load configuration
. /etc/bismark/bismark.conf
. /etc/bismark/bismark-lite.conf

# Create temporary tree
mkdir -p /tmp/bismark/var

# Pull device specific configuration from the server
#action config pull

# Set boot event and start modem monitor
# bismark-event boot
# bismark-event modem

# Set the device identifier
if [[ ! -e /etc/bismark/ID ]]; then
	(echo -n OW; ifconfig $LAN_IF | awk '/HWaddr / { gsub(":","", $5); print $5 }' ) > /etc/bismark/ID
fi

bismark-bootstrap-lite scriptupdate
# Cronjobs setup
cat /etc/crontabs/root /etc/bismark/crontab-lite | sort -u | crontab -

