#!/bin/ash
# Bismark shaperprobe wrapper (output in Kbps)
#
# author: walter.dedonato@unina.it

# Load configuration file
. /etc/bismark/bismark.conf
. "$BROOT"/etc/bismark/bismark-active.conf
. /usr/lib/bismark/functions.inc.sh

# Help screen
[ $2 ] || { echo "usage: $(basename $0) <dst_ip> <dst_port>" ; exit ; }

# Get measure info 
get_ip
dst=$1
port=$2
tstamp=$(date +%s)

/usr/bin/prober -s $dst -p $port | awk '
	BEGIN{ RS="[\r\n]" }
	/^Upstream:/{ print "\t<measurement param=CAPACITY tool=SP srcip='$src' dstip='$dst' timestamp='$tstamp' avg=" $2 " std=0 min=" $2 " max=" $2 " med=" $2 " iqr=0 direction=\"up\" />" }
	/^Downstream:/{  print "\t<measurement param=CAPACITY tool=SP srcip='$dst' dstip='$src' timestamp='$tstamp' avg=" $2 " std=0 min=" $2 " max=" $2 " med=" $2 " iqr=0 direction=\"dw\" />" }
	/^Up:/{ print "\t<measurement param=SHAPERATE tool=SP srcip='$src' dstip='$dst' timestamp='$tstamp' avg=" $2 " std=0 min=" $2 " max=" $2 " med=" $2 " iqr=0 direction=\"up\" />" }
	/^Down:/{ print "\t<measurement param=SHAPERATE tool=SP srcip='$dst' dstip='$src' timestamp='$tstamp' avg=" $2 " std=0 min=" $2 " max=" $2 " med=" $2 " iqr=0 direction=\"dw\" />" }
'

