#!/bin/ash
# Device sysctl settings
# Reads /etc/bismark/sysctl.conf and /tmp/bismark/sysctl.conf
# and sets sysctl
# author: srikanth@gatech.edu

. /etc/bismark/bismark.conf
. "$BROOT"/etc/bismark/bismark-active.conf
. /usr/lib/bismark/functions.inc.sh

files=$BROOT"/etc/bismark/sysctl.conf /tmp/bismark/sysctl.conf"
for file in $files; do
	if [ -e $file ]; then
		sysctl -p $file
 	fi
done 
