#!/bin/ash
# Bismark ditg wrapper (output in Kbps)
#
# author: walter.dedonato@unina.it

# Load configuration file
. /etc/bismark/bismark.conf
. "$BROOT"/etc/bismark/bismark-active.conf
. /usr/lib/bismark/functions.inc.sh

# Settings
DATA_DIR=/tmp/bismark/active/ditg

# Help screen
[ $6 ] || { 
	echo "usage: $(basename $0) tcp <target> <port> <up|dw> <duration> <kbps>"
	echo "       $(basename $0) udp <target> <port> <up|dw> <duration> <pps>" 
	echo "       $(basename $0) udpflood <target> <port> <up|dw> <duration> <kbps>" 
	exit
}

# AWK log filter
filter='
	/bitrate/{ out="bitrate.txt" ; next }
	/jitter/{  out="jitter.txt" ; next }
	/pktloss/{ out="packetloss.txt" ; next }
	(out != ""){ print >> out }
'

# Change path
mkdir -p $DATA_DIR
cd $DATA_DIR
[ -e itgfifo ] || mkfifo itgfifo
get_ip
tstamp=$(date +%s)

# Select protocol
case $1 in
tcp)
	pkt_size=$DITG_TCP_PKTSIZE
	pkt_rate=$(( ((${6}000 / 8) / $pkt_size) + 1 ))

	# Select direction
	case $4 in
	up)  
		/usr/bin/ITGSend -a $2 -rp 0 -T TCP -c $pkt_size -C $pkt_rate -t ${5}000 -x /tmp/${DEVICE_ID}_$tstamp.log  >/dev/null 2>&1 
		echo "log /tmp/${DEVICE_ID}_$tstamp.log" | nc -n $2 $3 | awk "$filter"
		cat bitrate.txt | "$BROOT"/usr/bin/bismark-mstats BITRATE DITG $src $2 $4 | grep -v nan
	;;
	dw)
		port=$(random 5000 15000)
		{ echo "send -H -Ssp $port -rp 0 -T TCP -c $pkt_size -C $pkt_rate -t ${5}000" ; sleep 2 ; } | nc $NC_OPTS $2 $3
		/usr/bin/ITGRecv -H $2 -Sp $port -l itgfifo.dat > /dev/null 2>&1
		/usr/bin/ITGDec itgfifo.dat -b 1000 > /dev/null 2>&1
		rm itgfifo.dat
		awk '(NR > 1){ print $3 }' bitrate.txt | "$BROOT"/usr/bin/bismark-mstats BITRATE DITG $2 $src $4
	;;
	esac
;;
udp)
	pkt_size=$DITG_UDP_PKTSIZE
	pkt_rate=$6

	# Select direction
	case $4 in
	up)  
		/usr/bin/ITGSend -a $2 -rp 0 -T UDP -c $pkt_size -C $pkt_rate -t ${5}000 -x /tmp/${DEVICE_ID}_$tstamp.log  >/dev/null 2>&1
		echo "log /tmp/${DEVICE_ID}_$tstamp.log" | nc -n $2 $3 | awk "$filter"
		cat jitter.txt | "$BROOT"/usr/bin/bismark-mstats JITTER DITG $src $2 $4 | grep -v nan
		awk '{ print $1/'$pkt_rate' }' packetloss.txt | "$BROOT"/usr/bin/bismark-mstats PKTLOSS DITG $src $2 $4
	;;
	dw)
		RANDOM=$(( `date +%s` % 32767 ))
		port=$(( RANDOM % 5000 + 10000 ))
		{ echo "send -H -Ssp $port -rp 0 -T UDP -c $pkt_size -C $pkt_rate -t ${5}000" ; sleep 2 ; } | nc $NC_OPTS $2 $3
		/usr/bin/ITGRecv -H $2 -Sp $port -l itgfifo.dat > /dev/null 2>&1 
		/usr/bin/ITGDec itgfifo.dat -p 1000 -j 1000 > /dev/null 2>&1
		rm itgfifo.dat
		awk '(NR > 1){ print $3 }' jitter.txt | "$BROOT"/usr/bin/bismark-mstats JITTER DITG $2 $src $4
		awk '(NR > 1){ print $3/'$pkt_rate' }' packetloss.txt | "$BROOT"/usr/bin/bismark-mstats PKTLOSS DITG $2 $src $4
	;;
	esac
;;
udpflood)
	pkt_size=$DITG_UDPFLOOD_PKTSIZE
	pkt_rate=$(( ((${6}000 / 8) / $pkt_size) + 1 ))

	# Select direction
	case $4 in
	up)  
		/usr/bin/ITGSend -a $2 -rp 0 -T UDP -c $pkt_size -C $pkt_rate -t ${5}000 -x /tmp/${DEVICE_ID}_$tstamp.log  >/dev/null 2>&1 
		echo "log /tmp/${DEVICE_ID}_$tstamp.log" | nc -n $2 $3 | awk "$filter"
		cat bitrate.txt | "$BROOT"/usr/bin/bismark-mstats UDPBITRATE DITG $src $2 $4 | grep -v nan
	;;
	dw)
		RANDOM=$(( `date +%s` % 32767 ))
		port=$(( RANDOM % 5000 + 10000 ))
		{ echo "send -H -Ssp $port -rp 0 -T UDP -c $pkt_size -C $pkt_rate -t ${5}000" ; sleep 2 ; } | nc $NC_OPTS $2 $3
		/usr/bin/ITGRecv -H $2 -Sp $port -l itgfifo.dat > /dev/null 2>&1
		/usr/bin/ITGDec itgfifo.dat -b 1000 > /dev/null 2>&1
		rm itgfifo.dat
		awk '(NR > 1){ print $3 }' bitrate.txt | "$BROOT"/usr/bin/bismark-mstats UDPBITRATE DITG $2 $src $4
	;;
	esac
;;
esac

rm -f bitrate.txt jitter.txt packetloss.txt

