#!/bin/ash
# Transfers files to the bismark server
#
# author: walter.dedonato@unina.it

# Load configuration file
. /etc/bismark/bismark.conf

# Help screen
[ $2 ] || { echo "usage: $(basename $0) <up|dw> <file1> [...]" ; exit ; }

# Copy files using scp
case $1 in
up)
	shift
	for file in $*; do
		scp -i $SSH_KEY $file $USER@$SERVER:~/bismark/device/$PLATFORM/$file
	done
;;
dw)
	shift
	for file in $*; do
		scp -i $SSH_KEY $USER@$SERVER:~/bismark/device/$PLATFORM/$file $file
	done
;;
esac
