#!/bin/ash
# Device startup script
#
# author walter.dedonato@unina.it
# modified by srikanth@gatech.edu

# Load configuration
. /etc/bismark/bismark.conf

# Create temporary tree
mkdir -p /tmp/bismark/var

# Pull device specific configuration from the server

# Set the device identifier
if [ ! -e /etc/bismark/ID ]; then
	(echo -n OW; ifconfig $LAN_IF | awk '/HWaddr / { gsub(":","", $5); print $5 }' ) > /etc/bismark/ID
	uci set system.@system[0].hostname=`cat /etc/bismark/ID`
	uci commit system
fi

# Cronjobs setup
if [ -e /etc/bismark/crontab-active ]; then
	cat /etc/bismark/crontab-active > /tmp/bismark-crontab-active
elif [ -e /tmp/etc/bismark/crontab-active-tmpfs ]; then
	cat /tmp/etc/bismark/crontab-active-tmpfs > /tmp/bismark-crontab-active
else
	echo -n '' > /tmp/bismark-crontab-active
fi
cat /etc/crontabs/root /etc/bismark/crontab /tmp/bismark-crontab-active | sort -u > /tmp/bismark-crontab
cmp -s /etc/crontabs/root /tmp/bismark-crontab
if [ $? -gt 0 ]; then
	cat /tmp/bismark-crontab | crontab -
fi
rm /tmp/bismark-crontab-active
rm /tmp/bismark-crontab

if [ -e /www/index.html ] && [ -e /www/index.htm ]; then
	rm -f /www/index.html
fi

DEVID=`cat /etc/bismark/ID`
if [ `grep -c $DEVID /etc/opkg.conf` -eq 0 ]; then                                        
        sed -i -e "s!updates-device!updates-device/$DEVID!g" /etc/opkg.conf 
        sed -i -e "s!experiments-device!experiments-device/$DEVID!g" /etc/opkg.conf  
fi

#Conf changes
bismark-action mgmtconfupdate
bismark-action scriptupdate

#Restart cron
/etc/init.d/cron stop
/etc/init.d/cron start
