#!/bin/ash
# Device actions script
# Provides:
# - on-demand SSH tunnel
# - server heartbeat
# - software update
# - configuration query/pull
#
# author: walter.dedonato@unina.it
# modified by srikanth@gatech.edu

# Import configuration and functions
. /etc/bismark/bismark.conf
. /usr/lib/bismark/functions.inc.sh

# Help screen
[ $1 ] || { echo "$(basename $0) <command> [options]" ; exit ; }

# Perform the requested action
case $1 in
fwd)	# on-demand SSH tunnel
	if [ $2 == ${2#*:} ]; then
		# Default to local port $MGMT_SSHD_PORT
		( ssh -y $KEEP_ALIVE -N -i $SSH_KEY -R $2:127.0.0.1:$MGMT_SSHD_PORT $USER@$SERVER >/dev/null 2>&1 & )
	else
		# To custom IP:PORT destination
		( ssh -y $KEEP_ALIVE -N -i $SSH_KEY -R $2 $USER@$SERVER >/dev/null 2>&1 & )
	fi
;;
pong)	# Server heartbeat
	ltime=$(date +%s)
	echo $ltime > /tmp/bismark/var/server_last

	# Store public IP
	echo $2 > /tmp/bismark/var/ip
;;
mgmtconfupdate) # mgmt conf update
	dl_file "$MGMT_CONF_URL" /tmp/bismark/local.conf
;;
scriptupdate) # script file update
	dl_file "$SCRIPT_URL" /tmp/bismark/$DEVICE_ID.sh
	chmod 544 /tmp/bismark/$DEVICE_ID.sh
;;
esac
