#!/bin/ash
# Executes a measurement cycle
# 
# author: walter.dedonato@unina.it

# Load configuration file
. /etc/bismark/bismark.conf
. /usr/lib/bismark/functions.inc.sh

# Measure message generator
# $1 = options
msg () 
{
	echo "$DEVICE_ID measure $1"
	sleep 3
}

# Get target info
# $1 = category
# $2 = type
# $3 = zone
# $4 = duration
get_target ()
{
	# Send message
	msg "$1 $2 $3 $4" | nc -u $NC_OPTS $SERVER $PROBE_PORT > /tmp/mreply

	# Get reply
	read dst info wait < /tmp/mreply
	[ $dst ] || return 1 
}

# Create dirs and files
mkdir -p /tmp/measure
[ -e /tmp/measure/counter ] || echo 0 > /tmp/measure/counter

# Get and update count
count=$(cat /tmp/measure/counter)
echo $(( (count + 1) % 288 )) > /tmp/measure/counter

# Random wait
sleep $((RANDOM % 3))

# Globals
xml_file="/tmp/${DEVICE_ID}_$(date +%s).xml"

# Get source IP
get_ip

# XML file header
cat > $xml_file <<-end
	<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
	<measurements version="1.2">
	        <info deviceid=$DEVICE_ID />
end

## Concurrent measurements ##
count=0
if [ $((count % TR_FQ)) -eq 0 ]; then
	# Traceroute
	if get_target Bismark TR $ZONE 0 ; then
		hops=$(bismark-tr $dst)
		hops_cnt=$(echo "$hops" | wc -l)
		if [ $hops_cnt -gt 0 ]; then
			cat >> $xml_file <<-end
			        <traceroute srcip=$src dstip=$dst timestamp=$(date +%s) hops=$hops_cnt>
				$(echo "$hops" | awk '{ print "                " $0 }')
			        </traceroute>
			end
		fi
		gwip=$(cat /tmp/gwip)
	fi

	# Reverse traceroute
	if get_target Bismark RTR $ZONE 0 ; then
		hops=$(bismark-rtr $dst $info)
		hops_cnt=$(echo "$hops" | wc -l)
		if [ $hops_cnt -gt 0 ]; then
			cat >> $xml_file <<-end
			        <traceroute srcip=$dst dstip=$src timestamp=$(date +%s) hops=$hops_cnt>
				$(echo "$hops" | awk '{ print "                " $0 }')
			        </traceroute>
			end
		fi
	fi
fi
echo "Done TR"
# Get Gateway IP
if [ ! "$gwip" ]; then
	bismark-tr "8.8.8.8" > /dev/null
	[ -e /tmp/gwip ] && gwip=$(cat /tmp/gwip)
fi

# RTT measurements using PING
if get_target Bismark PING $ZONE 10 ; then
	# Last mile RTT
	if [ "$gwip" ]; then
		( bismark-ping $gwip | bismark-mstats LMRTT PING $src $gwip > /tmp/lmrtt ; cat /tmp/lmrtt >> $xml_file ) &
	fi

	# Geo-distributed servers RTT
	mkdir -p /tmp/gdrtt
	for srv in $(grep -v ^# /usr/lib/bismark/world_ips.list); do
		( bismark-ping $srv | bismark-mstats RTT PING $src $srv > /tmp/gdrtt/$srv ; cat /tmp/gdrtt/$srv >> $xml_file ) &
	done

	# MServer RTT
	bismark-ping $dst | bismark-mstats RTT PING $src $dst >> $xml_file 
fi
echo "Done PING"
# DNS delay and failure
if [ $((count % DNS_FQ)) -eq 0 ]; then
	bismark-dns >> $xml_file
fi
echo "Done DNS"

## Serial measurements ##
if [ ! -e /tmp/mlock ]; then 
	# Set measure lock
	echo $(date +%s) > /tmp/mlock

	# Bitrate
	if [ $((count % BR_FQ)) -eq 0 ]; then
		# Downstream bitrate using NETPERF
		if get_target Bismark NETPERF $ZONE $BR_DURATION ; then
			sleep $wait
			( sleep 3 ; bismark-ping $dst | bismark-mstats ULRTTDW PING $src $dst >> $xml_file ) &
			bismark-netperf $BR_DURATION $NTHREADS $dst dw | bismark-mstats BITRATE NETPERF $dst $src | grep -v nan >> $xml_file
		fi

		# Upstream bitrate using NETPERF
		if get_target Bismark NETPERF $ZONE $BR_DURATION ; then
			sleep $wait
			( sleep 3 ; bismark-ping $dst | bismark-mstats ULRTTUP PING $src $dst >> $xml_file ) &
			bismark-netperf $BR_DURATION $NTHREADS $dst up | bismark-mstats BITRATE NETPERF $src $dst | grep -v nan >> $xml_file
		fi
	fi

	# Jitter & Packet loss using DITG
	if [ $((count % UDP_FQ)) -eq 0 ]; then
		# Downstream 
		if get_target Bismark ITGDL $ZONE $UDP_DURATION ; then
			sleep $wait
			bismark-ditg udp $dst $info dw $UDP_DURATION $UDP_PPS >> $xml_file
		fi

		# Upstream
		if get_target Bismark ITGUL $ZONE $UDP_DURATION ; then
			sleep $wait
			bismark-ditg udp $dst $info up $UDP_DURATION $UDP_PPS >> $xml_file
		fi
	fi

	# Shaper probe
	if [ $((count % SP_FQ)) -eq 0 ]; then
		if get_target Bismark SP $ZONE 150 ; then
			sleep $wait
			bismark-sp $dst >> $xml_file
		fi
	fi

	# Release measure lock
	rm /tmp/mlock
else
	# Check lock
	locktime=$(cat /tmp/mlock)
	currtime=$(date +%s)
	if [ $((currtime - locktime)) -gt 400  ]; then
		killall netperf prober ITGRecv ITGSend
		rm /tmp/mlock
	fi
fi
echo "Done ALL"

# XML file footer
cat >> $xml_file <<-end
	</measurements>
end

# Move file to measure folder
sleep 2
mv $xml_file /tmp/measure

# Upload result 

