#!/bin/ash
# Bismark arp wrapper
#
# author: walter.dedonato@unina.it

# Load configuration files
. /etc/bismark/bismark.conf

# Dump arp table 
arp -n | awk '(NR > 1 && /ether/){ print '$(date +%s)' "\t" $1 "\t" $3}' >> /tmp/bismark/data/${DEVICE_ID}.arp
