#!/bin/bash
# Bismark airodump wrapper
#
# author: walter.dedonato@unina.it

# Load configuration files
. ~/conf/dev.conf

# Enable monitor interface 
if ! (/sbin/ifconfig | grep -q ath1) ; then
	/sbin/wlanconfig ath1 create wlandev wifi0 wlanmode monitor
	/sbin/ifconfig ath1 up
fi

# Start/Restart airodump and stop after 5 minutes
if [ $(pgrep -n airodump-ng) ]; then
	killall airodump-ng
	mv /tmp/${DEVICE_ID}*.csv /tmp/measure
fi

if [ "$1" == all ]; then
	( openvt -w airodump-ng -w /tmp/${DEVICE_ID}_$(date +%s)_all --output-format csv --berlin 500 ath1 & )
else
	( openvt -w airodump-ng -w /tmp/${DEVICE_ID}_$(date +%s) --channel $WIFI_CHANNEL --output-format csv --berlin 500 ath1 & )
fi
