#!/bin/bash
# Send UDP probes to Bismark server and
# call action script depending on the answer
# Provides:
# - device heartbeat
# - UDP proxy fallback
# - startup script during boot
#
# author: walter.dedonato@unina.it

# Load configuration file
. $BISMARK_DIR/etc/bismark.conf

# Probe message generator
msg () {
	echo "$DEVICE_ID ping $VERSION"
	sleep 1
	return 0
}

# Create status files
[ -e $BISMARK_DIR/var/faults ] || echo 0 > $BISMARK_DIR/var/faults
[ -e $BISMARK_DIR/var/proxy ] || echo 0 > $BISMARK_DIR/var/proxy

# Check faults count
faults=$(cat $BISMARK_DIR/var/faults)
if [ $faults -ge 20 ]; then
	proxy=$(cat /tmp/proxy)
	echo $(( (proxy + 1) % 2 )) > $BISMARK_DIR/var/proxy
	echo 0 > $BISMARK_DIR/var/faults
	faults=0
fi

# Random wait
sleep $((RANDOM % 30))

# Send probe and store reply
if [ $(cat $BISMARK_DIR/var/proxy) -eq 1 ]; then
	msg | nc -u $NC_OPTS $PROXY $PROXY_PORT > $BISMARK_DIR/var/reply
else
	msg | nc -u $NC_OPTS $SERVER $PROBE_PORT > $BISMARK_DIR/var/reply
fi

# Refresh faults count
if [ "`cat /tmp/reply`" ]; then
	echo 0 > /tmp/faults
	event uplink up
else
	echo $((++faults)) > /tmp/faults
	event uplink down
fi

# Parse reply
read cmd value < /tmp/reply
[ $cmd ] && REMOTE=on action $cmd $value

